USE sakila;

SELECT columns
FROM table1
INNER JOIN table2
ON table1.column_name = table2.column_name;

SELECT COUNT(city.city_id)
FROM country 
INNER JOIN city 
USING(country_id)
WHERE country.country = "Canada";

# List the number of films per category. ( #film.title & category.name)
SELECT cat.name, COUNT(f.film_id) as cat_count
FROM category as cat
INNER JOIN film_category as f
ON cat.category_id = f.category_id
GROUP BY cat.name
ORDER BY cat_count DESC;
 
# Retrieve the store ID, city, and country for each store. (store.address_id & address.country_id & city.city_id) 
SELECT store.store_id, city.city, country.country
FROM store
INNER JOIN address
USING(address_id)
INNER JOIN city
USING(city_id)
INNER JOIN country
USING(country_id);

# Calculate the total revenue generated by each store in dollars.
# (payment(amount).staff_id --> staff.store_id --> store.store_id)

SELECT store.store_id, SUM(payment.amount)
FROM payment
INNER JOIN staff
USING(staff_id)
INNER JOIN store
USING(store_id)
GROUP BY store.store_id;

# Determine the average running time of films for each category.
# film(length) --> film_category using film_id --> category(name) using category_id
SELECT category.name, AVG(film.length) avg_length
FROM film
INNER JOIN film_category
USING(film_id)
INNER JOIN category
USING(category_id)
GROUP BY category.name
ORDER BY avg_length DESC;


